version: '3'

services:
  web:
    container_name: web-container
    image: promng_web:latest
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    depends_on:
      - app

  app:
    container_name: app-container
    image: promng_app:latest
    command: python3 manage.py runserver 0.0.0.0:30000
    ports:
      - "30000:30000"
    depends_on:
      - db

  db:
    container_name: db-container
    image: promng_db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: apuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: promng
      TZ: "Asia/Tokyo"
      BIND-ADDRESS: 0.0.0.0
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    tty: true